### ISSUE TITLE
run 一行内删除临时文件才有用

### ISSUE THREAD

**Issue by fananchong** [mostevercxz/centos8-gcc10-llvm11-env#1]
![image](https://user-images.githubusercontent.com/20277955/101315641-ec429080-3895-11eb-9313-5f2032f130d9.png)
这种是bug

你这个 5G  还可以缩小空间还有很多很多。

**Comment by mostevercxz** [comment]
## 使用 multi-stage build 后，容器大小降为 6.28G，暂时只能先这样了，毕竟装了太多软件。参见提交：

https://github.com/mostevercxz/centos8-gcc10-llvm11-env/commit/e98e3fc11cc75df62c8c29368b3a5f2dfcce3680



```bash
[root@localhost centos8-gcc10-llvm11-env]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
serverdev           latest              0cb598a3c138        11 minutes ago      6.28GB
```
